Add new functionality for returning an x509 file
open-power/sb-signing-framework pull request #17
Opened 2021-02-11 22:42 UTC by nick-child-ibm

In this commit, I ported Ken Goldman's x509 generator code from 2013. This will allow for a client to request an x509 version of their public key. The x509 can be either self signed or signed from a CA, depending on priviledges. The system administrator can make a CA by generating a new key with an auxiliary file containing signature/digest algorithms, validity, final and Issuer fields. The significance of these fields can be found in Kens documentation. The key to be signed in the ceritficate can be a any project if the certifying key is declared as final. If not, then an auxiliary file will be needed for the key to be certified. This will contain all the same fields as the ceritifying aux file. If the certifying key is listed as final than this means that it is the final issuer in the certificate chain, it will be used to sign other projects only. The auxiliary file for these final issuers must also contain subject fields that describes the project it is signing. This is all described in kens documentation. To request an x509 from the server side, the user can run './sf_client ./sf_client -project <project name1> -comments "Testing sign cert" -param "-certify_project <project name2> -usr <userid>" -url sftp://<userid>@argus4.rch.stglabs.ibm.com -epwd <encrypted pswd> -pkey <rsa_private> ' where <project name1> is certifying/signing <project_name2> .
NOTE: You will likely need to increase the file_max field of your framework config, since x509s are larger than other outputed filed
This commit also comes with testing scripts. To run, follow the below steps:
1. run keygen commands described in generateTestFiles.sh
2. Add yourself to senders in the config files for issuer_final issuer_root code_signer
3. run generateTestFiles.sh
4. export FRAMEWORK_CONFIG_FILE to point to regression.cfg
5. run the framework
6. switch over to the client machine
7. fill in user specific fields in sign_cert_test.sh
8. run sign_cert_test.sh

Kens Documentation:
[sign_cert documentation](https://github.com/open-power/sb-signing-framework/files/5968809/sign_cert_pdf.pdf)

2021-02-11 22:59 UTC, cjengel commented on src/signframework/sign_cert/cca_functions.c
> +/* Copyright 2017 IBM Corp.
The current design could use fixing but common routines like cca_function.c/h exist in the signframework directory and then the various tools just create a link to it .  So if there are changes in here they should be merged into the main copy and links inserted in sign_cert to ../cca_functions.c

2021-02-16 18:50 UTC, mtvaught-ibm requested changes
Only looked through the function code c/h files so far, comparing them to Ken's original code.

The "generation" of the regression test config files don't make sense to me. Why not just generate them once and them commit them under the test/ directory? Then they just exist and the tester can point FRAMEWORK_CONFIG_FILE to the testing config?

2021-02-16 18:52 UTC, mtvaught-ibm commented
A handful of the files you pushed up have a  IBM Confidential license header on them. Please discuss with @cjengel and Ken to determine what the correct licensing of these files are and update the headers accordingly.

2021-02-17 16:30 UTC, nick-child-ibm commented
> Only looked through the function code c/h files so far, comparing them to Ken's original code.
> 
> The "generation" of the regression test config files don't make sense to me. Why not just generate them once and them commit them under the test/ directory? Then they just exist and the tester can point FRAMEWORK_CONFIG_FILE to the testing config?

Well I was worried about committing static files that were only used for testing. Are you guys planning on shipping this project with test scripts/files (noticing now that no other features have testing data)? If no, then I can commit the the static files and you folks can remove them before merging. Otherwise, I would think it would make more sense from a tester perspective to see where/why/how these files were generated and I always think it makes more sense to generate static files rather than shipping them. Also, if we choose to push the test files, should I remove the generator script? Let me know your thoughts and I can make the appropriate fixes.

2021-02-17 16:58 UTC, nick-child-ibm commented on src/signframework/sign_cert/makefile
> +	rm *.o sign_cert
If we decide to keep the test file generator script then this does the cleanup for it.

2021-02-17 18:44 UTC, mtvaught-ibm commented on src/signframework/sign_cert/makefile
> +	rm *.o sign_cert
My point is that the the test file generator script has nothing to do with building the project. So it is strange to have the cleanup for that script as part of the makefile.

2021-02-17 18:48 UTC, mtvaught-ibm commented
> > Only looked through the function code c/h files so far, comparing them to Ken's original code.
> > The "generation" of the regression test config files don't make sense to me. Why not just generate them once and them commit them under the test/ directory? Then they just exist and the tester can point FRAMEWORK_CONFIG_FILE to the testing config?
> 
> Well I was worried about committing static files that were only used for testing. Are you guys planning on shipping this project with test scripts/files (noticing now that no other features have testing data)? If no, then I can commit the the static files and you folks can remove them before merging. Otherwise, I would think it would make more sense from a tester perspective to see where/why/how these files were generated and I always think it makes more sense to generate static files rather than shipping them. Also, if we choose to push the test files, should I remove the generator script? Let me know your thoughts and I can make the appropriate fixes.

This project doesn't get "shipped" in the conventional sense (or at least, not to my knowledge). On an install to a system the entire project is pulled and then compiled.

I'll let @cjengel weigh in on whether he sees an issue with having test files directly committed.

Perhaps a middle-ground would be to create a src/test directory to house the testing files and then have a script that could copy them out of src/test and into src/signframework. That would keep them out of the main framework on deployed systems, but also make it easier to see/edit the test files in the future.

2021-02-18 15:30 UTC, nick-child-ibm commented
Sounds good, I have no problem doing either. Let me know what you guys think is best and I will make the adjustments. Then, I can fix the test cleanup.

2021-03-08 18:54 UTC, cjengel commented on src/client/sign_cert_test.sh
> +#			       IBM Confidential
You missed a license header

2021-03-08 19:05 UTC, cjengel requested changes
Only issue I see is the one license header.  Need Matt to review as well.

2021-03-26 14:12 UTC, mtvaught-ibm requested changes
Need to remove IBM information, but other than that I think it is good to go.

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_final_sample.cfg
> +email=nick.child@ibm.com
You may want to remove your email

The other sample configs use joe@example.com

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_final_sample.cfg
> +nnac=nick.child@ibm.com
You may want to remove your email/id

The other sample configs use fred=fred@example.com

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_final_sample_aux.cfg
> +issuerCountryName=US
Remove IBM specific things

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_final_sample_aux.cfg
> +subjectCountryName=US
same here

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_final_sample_aux.cfg
> +validity=20
Maybe pick a more "standard" validity range. I think the "standard" right now is a max of 2 years?

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_root_sample.cfg
> +nnac=nick.child@ibm.com
Change to non-identifying id/email

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_root_sample.cfg
> +email=nick.child@ibm.com
change to non-identifying email

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_root_sample.cfg
> +# $Id: issuer_root_sample.cfg 424 2013-12-20 19:20:07Z kgoldman $
remove

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_root_sample_aux.cfg
> +sign_algorithm=RSA-2048
remove IBM information

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_root_sample_aux.cfg
> +validity=20
max 2 years

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/code_signer_sample.cfg
> +email=nick.child@ibm.com
email

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/code_signer_sample.cfg
> +nnac=nick.child@ibm.com
email/id

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/base_regression.cfg
> +ldapurl=ldap://bluepages.ibm.com:389
remove IBM ldap information

2021-03-26 14:12 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/base_regression.cfg
> +nick.child@ibm.com
change to something generic

2021-03-26 18:59 UTC, mtvaught-ibm requested changes

2021-03-26 18:59 UTC, mtvaught-ibm commented on src/signframework/sign_cert/tests/issuer_root_sample.cfg
> +# $Id: issuer_root_sample.cfg 424 2013-12-20 19:20:07Z kgoldman $
Still need to remove this line

2021-04-08 17:59 UTC, nick-child-ibm commented
Let me know if there is anything else I can do.

2021-04-22 19:37 UTC, cjengel commented
Looks good to me

2021-04-22 19:43 UTC, mtvaught-ibm approved these changes
@cjengel This PR should be merged using "squash and merge"

2021-04-22 19:47 UTC, merged